######################################################################
# Automatically generated by qmake (2.00a) Sat Jan 7 20:52:19 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += src/dbwindow.h src/dialogs.h src/mainwindow.h src/images/kaccess.xpm
SOURCES += src/dbwindow.cpp src/dialogs.cpp src/kaccess.cpp src/mainwindow.cpp
