SOURCES	+= dbwindow.cpp \
	mainwindow.cpp \
	main.cpp \
	widgets.cpp
HEADERS	+= dbwindow.h \
	mainwindow.h \
	widgets.h
######################################################################
# Automatically generated by qmake (1.06c) Tue Mar 15 20:15:02 2005
######################################################################


# Input
TEMPLATE	=app
INCLUDEPATH	+= .
LANGUAGE	= C++
