TEMPLATE	= app
LANGUAGE	= C++

INCLUDEPATH	+= .

HEADERS	+= dbwindow.h \
	mainwindow.h \
	tabledesigner.h \
	widgets.h

SOURCES	+= dbwindow.cpp \
	main.cpp \
	mainwindow.cpp \
	tabledesigner.cpp \
	widgets.cpp

######################################################################
# Automatically generated by qmake (1.06c) Fri Mar 18 16:40:35 2005
######################################################################


# Input
INCLUDEPATH	+= .
